# Generated by Django 4.2 on 2023-06-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_chargingport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chargingport",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="chargingport",
            name="port_number",
            field=models.IntegerField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="charging_port",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.chargingport",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="minutes_paid",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
